#!/bin/bash

# USE:
#     find $srcdir -type f -print0 | xargs -0 -L25 -P4 /path/to/import-photos $dstdir
#
# DEPENDENCIES:
#     sha2 to calculate file digests
#     exif to get date and time stamp from images
#     ffmpeg to get date and time stamp from movies

SHA2=$(which sha2)
if [ -z "$SHA2" ] ; then
    echo >&2 "install 'sha2' in order to calculate file digests."
    exit 1
fi

EXIF=$(which exif)
if [ -z "$EXIF" ] ; then
    echo >&2 "install 'exif' in order to get date and time stamps from images."
    exit 1
fi

FFMPEG=$(which ffmpeg)
if [ -z "$FFMPEG" ] ; then
    echo >&2 "install 'ffmpeg' in order to get date and time stamps from videos."
    exit 1
fi

MDLS=$(which mdls)

# DEFAULTS
copymove=mv
tfix=

OPTIND=1
while getopts :ct option 2>/dev/null ; do
    case $option in
        c) copymove=cp ;;
        t) tfix=true ;;
        \:) echo >&2 "option [$OPTARG] requires an argument" ; exit 2 ;;
        \?) echo >&2 "unknown argument [$OPTARG]" ; exit 2 ;;
    esac
done
shift $(($OPTIND-1))

case $# in
    0) echo >&2 "usage: $(basename $0) [-c] [-t] destdir file1 file2..."
       exit 2
       ;;
    *) destdir=$1
       shift
       ;;
esac

for src ; do
    if [ ! -f "$src" ] ; then
        echo >&2 "cannot import file: $src"
        continue
    fi

    digest=$($SHA2 -q -256 "$src")
    if [ -z "$digest" ] ; then
        echo >&2 "empty file digest: $src"
        exit 1
    fi

    extension=$(tr A-Z a-z <<< "${src##*.}")

    case $extension in
        jpg|jpeg)
            datetime=$($EXIF -m -t DateTimeOriginal "$src")
            if [ $? -ne 0 -o -z "$datetime" ] ; then
                datetime=$($EXIF -m -t DateTime "$src")
                if [ $? -ne 0 -o -z "$datetime" ] ; then
                    datetime="??"
                fi
            fi
            case $datetime in
                ??)
                if [ -z "$tfix" ] ; then
                    echo >&2 "cannot get date time: $src"
                    continue
                fi
                dest=1970/01-01
                ;;
                *) dest="${datetime:0:4}/${datetime:5:2}-${datetime:8:2}" ;;
            esac
            extension=jpg # jpeg -> jpg
            ;;
        heic|png)
            if [ -z "$MDLS" ] ; then
                echo >&2 "cannot get date time: $src"
                continue
            fi
            dest=$($MDLS -name kMDItemContentCreationDate "$src" | awk '{print substr($3,0,4) "/" substr($3,6,2) "-" substr($3,9,2)}')
            ;;
        avi|m4v|mov|mp4|3gp)
            dest=$($FFMPEG -i "$src" -dump 2>&1 | awk '$1 == "creation_time" {print substr($3,0,4) "/" substr($3,6,2) "-" substr($3,9,2) ; exit}')
            if [ $? -ne 0 -o -z "$dest" ] ; then
                if [ -z "$tfix" ] ; then
                    echo >&2 "cannot get date time: $src"
                    continue
                fi
                dest=1970/01-01
            fi
            ;;
        *)
            echo >&2 "unknown extension: $src"
            continue
            ;;
    esac

    # echo >&2 "[$src] -> [$dest]"
    mkdir -v -p $destdir/$dest
    $copymove "$src" "$destdir/$dest/${digest}.${extension}"
    if [ $? -ne 0 ] ; then
        echo >&2 "cannot copy picture into repos: $src"
        continue
    fi
done
