#!/bin/bash

# USE:
#     import-photos-worker [-c] [-t] [-v] -d destroot file1...
#
# DEPENDENCIES:
#     exiftime from the exiftags package to get date stamps from images
#     ffmpeg to get date stamps from movies
#     gif2png (optional) to convert GIF to PNG
#     mdls (optional) to get date stamps from media
#     openssh to calculate file digests

# DEFAULTS
copymove=mv
destroot=
tfix=
verbose=

OPTIND=1
while getopts :cd:e:f:g:m:s:tv option 2>/dev/null ; do
    case $option in
        c) copymove=cp ;;
        d) destroot="$OPTARG" ;;
        e) EXIF=$OPTARG ;;
        f) FFMPEG=$OPTARG ;;
        g) GIF2PNG=$OPTARG ;;
        m) MDLS=$OPTARG ;;
        s) DIGEST=$OPTARG ;;
        t) tfix=true ;;
        v) verbose="-v" ;;
        \:) echo >&2 "option [$OPTARG] requires an argument" ; exit 2 ;;
        \?) echo >&2 "unknown argument [$OPTARG]" ; exit 2 ;;
    esac
done
shift $(($OPTIND-1))

case $# in
    0) echo >&2 "usage: $(basename $0) [-c] [-t] [-v] -d destroot file1..."
       exit 2
       ;;
    *) : ;;
esac

if [ -z "$DIGEST" ] ; then
    DIGEST=$(which openssl)
    if [ $? -ne 0 ] ; then
        echo >&2 "install 'openssl' in order to calculate file digests."
        exit 1
    fi
fi

if [ -z "$EXIF" ] ; then
    EXIF=$(which exiftime)
    if [ $? -ne 0 ] ; then
        echo >&2 "install 'exiftags' in order to get date and time stamps from images."
        exit 1
    fi
fi

if [ -z "$FFMPEG" ] ; then
    FFMPEG=$(which ffmpeg)
    if [ $? -ne 0 ] ; then
        echo >&2 "install 'ffmpeg' in order to get date and time stamps from videos."
        exit 1
    fi
fi

if [ -z "$MDLS" ] ; then
    MDLS=$(which mdls) || MDLS=false
fi

if [ -z "$GIF2PNG" ] ; then
    GIF2PNG=$(which gif2png) || GIF2PNG=false
fi

for src ; do
    if [ ! -f "$src" ] ; then
        echo >&2 "cannot import file: $src"
        continue
    fi
    basename=$(basename "$src")
    if [ "${basename:0:2}" == "._" ] ; then
        echo >&2 "ignoring metadata file: $src"
        continue
    fi

    aae=
    basename="${src%.*}"
    extension=$(tr A-Z a-z <<< "${src##*.}")
    datestamp=
    dest=

    case $extension in
        gif)
            if [ "$GIF2PNG" != "false" ] ; then
                # convert GIF files to PNG or MNG
                safe=$($GIF2PNG -w "$src" 2>/dev/null)
                if [ -n "$safe" ] ; then
                    extension="png" # single frame GIF
                else
                    extension="mng" # multiple frame GIF
                fi
                dest="${basename}.${extension}"
                magick "$src" "$dest"
                if [ $? -ne 0 ] ; then
                    echo >&2 "cannot convert GIF to PNG, MNG: $src"
                    rm -f "$dest"
                    continue
                fi
                rm $verbose "$src"
                if [ $? -ne 0 ] ; then
                    echo >&2 "cannot remove original GIF: $src"
                fi
                src=$dest
            fi
            ;;
        jpg|jpeg)
            extension=jpg # convert jpeg extensions to jpg
            datestamp=$($EXIF "$src" 2>/dev/null | awk '{print $3 ; exit}')
            ;;
        avi|m4v|mov|mp4|3gp)
            datestamp=$($FFMPEG -i "$src" -dump 2>&1 | awk '$1 == "creation_time" {print substr($3,0,4) "/" substr($3,6,2) "-" substr($3,9,2) ; exit}')
            ;;
        mpg)
            datestamp=$($FFMPEG -i "$src" -dump 2>&1 | awk '$1 == "creation_time" {print substr($3,0,4) "/" substr($3,6,2) "-" substr($3,9,2) ; exit}')
            if [ -n "$datestamp" ] ; then
                echo "[$src] -> [$datestamp]"
            fi
            continue
            ;;
        heic|mng|png) : ;;
        aae) continue ;; # Apple image transformation file, does not contain actual image data
        *)
            # echo >&2 "unknown extension: $src"
            continue
            ;;
    esac

    if [ "$datestamp" != "" -a "$datestamp" != "??" ] ; then
        dest="${datestamp:0:4}/${datestamp:5:2}-${datestamp:8:2}"
        if [ "$dest" == "(nul)-" ] ; then
            echo >&2 "[$src] -> [$datestamp]"
            continue
        fi
    else
        # When previous logic could not determine date stamp, attempt to use
        # `mdls` to resolve.
        if [ "$MDLS" != "false" ] ; then
            # [ -n "$verbose" ] && echo >&2 "using $MDLS to resolve datestamp: $src"
            dest=$($MDLS -name kMDItemContentCreationDate "$src" | awk '{print substr($3,0,4) "/" substr($3,6,2) "-" substr($3,9,2)}')
        fi
        if [ -z "$dest" ] ; then
            if [ -z "$tfix" ] ; then
                echo >&2 "cannot get datestamp: $src"
                continue
            fi
            dest=1970/01-01
        fi
    fi

    # echo "[$src] -> [$dest]"
    # echo >&2 "src: $src"
    # echo >&2  "dest: $dest"
    # continue

    digest=$($DIGEST sha256 "$src" | awk '{print $NF}')
    if [ -z "$digest" ] ; then
        echo >&2 "empty file digest: $src"
        exit 1
    fi


    dir="$destroot/${digest:0:3}"
    mkdir $verbose -p "$dir"
    if [ $? -ne 0 ] ; then
        echo >&2 "cannot create directory: $dir"
        continue
    fi

    echo "$src" >> "$dir/${digest:3:61}"
    # registry="${digest:0:3}/${digest:3:61}"
    # echo "[$src] -> [$digest] -> [$registry]"
    continue

    mkdir $verbose -p "$destroot/$dest"
    $copymove $verbose "$src" "$destroot/$dest/${digest}.${extension}"
    if [ $? -ne 0 ] ; then
        echo >&2 "cannot transfer file into repos: $src"
        continue
    fi
done
