#!/bin/bash

# USE:
#     import-photos [-c] [-l limit] [-p parallel] [-t] [-v] -d destroot srcroot1...
#
# DEPENDENCIES:
#     import-photos-worker, in same directory as this program, which itself requires:
#         sha2 to calculate file digests
#         exif to get date stamps from images
#         ffmpeg to get date stamps from movies
#         mdls (optional) to get date stamps from media

worker=$(dirname $0)/import-photos-worker
if [ ! -x "$worker" ] ; then
    echo >&2 "cannot import without worker: $worker."
    exit 1
fi

# DEFAULTS
copymove=
destroot=
limit=
parallel=
tfix=
verbose=

OPTIND=1
while getopts :cd:l:p:tv option 2>/dev/null ; do
    case $option in
        c) copymove="-c" ;;
        d) destroot=$OPTARG ;;
        l) limit="-L${OPTARG}" ;;
        p) parallel="-P${OPTARG}" ;;
        t) tfix="-t" ;;
        v) verbose="-v" ;;
        \:) echo >&2 "option [$OPTARG] requires an argument" ; exit 2 ;;
        \?) echo >&2 "unknown argument [$OPTARG]" ; exit 2 ;;
    esac
done
shift $(($OPTIND-1))

case $# in
    0) echo >&2 "usage: $(basename $0) [-c] [-l limit] [-p parallel] [-t] [-v] -d destroot srcroot1..."
       exit 2
       ;;
    *) : ;;
esac

SHA2=$(which sha2)
if [ $? -ne 0 ] ; then
    echo >&2 "install 'sha2' in order to calculate file digests."
    exit 1
fi
SHA2="-s $SHA2"

EXIF=$(which exif)
if [ $? -ne 0 ] ; then
    echo >&2 "install 'exif' in order to get date stamps from images."
    exit 1
fi
EXIF="-e $EXIF"

FFMPEG=$(which ffmpeg)
if [ $? -ne 0 ] ; then
    echo >&2 "install 'ffmpeg' in order to get date and time stamps from videos."
    exit 1
fi
FFMPEG="-f $FFMPEG"

MDLS=$(which mdls)
[ -n "$MDLS" ] && MDLS="-m $MDLS"

for srcroot ; do
    find $srcroot -type f -print0 | xargs -0 $limit $parallel $worker "$EXIF" "$FFMPEG" "$MDLS" "$SHA2" $copymove $tfix $verbose -d $destroot
done
